{% set name = "qtimageformats" %}
{% set version = "6.9.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://download.qt.io/official_releases/qt/{{ version.rpartition('.')[0] }}/{{ version }}/submodules/{{ name }}-everywhere-src-{{ version }}.tar.xz
    sha256: ebe9f238daaf9bb752c7233edadf4af33fc4fa30d914936812b6410d3af1577c
    folder: {{ name }}

build:
  number: 0
  skip: true  # [osx and x86_64]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - pkg-config     # [unix]
    - bison          # [linux]
    - flex           # [linux]
    - gperf          # [linux]
    - jom            # [win]
    - msys2-bison    # [win]
    - msys2-flex     # [win]
    - msys2-gperf    # [win]
    - cmake
    - ninja
    - perl
  host:
    - qtbase-devel {{ version }}
    - libtiff {{ libtiff }}
    - libwebp {{ libwebp }}
  run_constrained:
    - qt-main >={{ version }},<7
    - qt >={{ version }},<7

test:
  commands:
    - test -f $PREFIX/lib/qt6/plugins/imageformats/libqtiff${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/lib/qt6/plugins/imageformats/libqwebp${SHLIB_EXT}  # [unix]
    - if not exist %PREFIX%\\Library\\lib\\qt6\\plugins\\imageformats/qtiff.dll exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\qt6\\plugins\\imageformats/qwebp.dll exit 1  # [win]

about:
  home: https://www.qt.io/
  license: LGPL-3.0-only
  license_file: {{ name }}/LICENSES/LGPL-3.0-only.txt
  license_family: LGPL
  summary: Cross-platform application and UI framework ({{ name[2:] }} libraries).
  description: |
    Qt helps you create connected devices, UIs & applications that run
    anywhere on any device, on any operating system at any time ({{ name[2:] }} libraries).
  doc_url: https://doc.qt.io/
  dev_url: https://github.com/qt/{{ name }}
