{% set name = "qtimageformats" %}
{% set version = "6.7.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  # Qt removed v6.7 from their Qt Downloads page to the archive
  - url: https://download.qt.io/archive/qt/{{ version.rpartition('.')[0] }}/{{ version }}/submodules/{{ name }}-everywhere-src-{{ version }}.tar.xz
    sha256: 9fd58144081654c3373768dd96ead294023830927b14fe3d3c1ef641fb324753
    folder: {{ name }}

build:
  number: 2
  skip: true  # [osx and x86_64]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - pkg-config  # [unix]
    - bison  # [linux]
    - flex  # [linux]
    - gperf  # [linux]
    - jom  # [win]
    - m2-bison  # [win]
    - m2-flex  # [win]
    - m2-gperf  # [win]
    - cmake
    - ninja
    - perl
  host:
    - qtbase-devel {{ version }}
    - libtiff {{ libtiff }}
    - libwebp {{ libwebp }}
  run_constrained:
    - qt-main >={{ version }},<7
    - qt >={{ version }},<7

test:
  commands:
    - test -f $PREFIX/lib/qt6/plugins/imageformats/libqtiff${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/lib/qt6/plugins/imageformats/libqwebp${SHLIB_EXT}  # [unix]
    - if not exist %PREFIX%\\Library\\lib\\qt6\\plugins\\imageformats/qtiff.dll exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\qt6\\plugins\\imageformats/qwebp.dll exit 1  # [win]

about:
  home: https://www.qt.io/
  license: LGPL-3.0-only
  license_file: {{ name }}/LICENSES/LGPL-3.0-only.txt
  license_family: LGPL
  summary: Cross-platform application and UI framework ({{ name[2:] }} libraries).
  description: |
    Qt helps you create connected devices, UIs & applications that run
    anywhere on any device, on any operating system at any time ({{ name[2:] }} libraries).
  doc_url: https://doc.qt.io/
  dev_url: https://github.com/qt/{{ name }}
